### ISSUE TITLE
FemtoVGRenderer is no longer available

### ISSUE THREAD

**Issue by MAlba124** [slint-ui/slint#11530]
### Bug Description

Enabling `slint/renderer-femtovg` does not work in 1.16.

```
error[E0432]: unresolved import `i_slint_renderer_femtovg::FemtoVGOpenGLRenderer`
   --> slint-1.16.1/lib.rs:417:17
    |
417 |         pub use i_slint_renderer_femtovg::FemtoVGOpenGLRenderer as FemtoVGRenderer;
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `FemtoVGOpenGLRenderer` in the root
    |
note: found an item that was configured out
   --> i-slint-renderer-femtovg-1.16.1/lib.rs:584:10
    |
583 | #[cfg(feature = "opengl")]
    |       ------------------ the item is gated behind the `opengl` feature
584 | pub type FemtoVGOpenGLRenderer = FemtoVGRenderer<opengl::OpenGLBackend>;
    |          ^^^^^^^^^^^^^^^^^^^^^
help: a similar name exists in the module
    |
417 -         pub use i_slint_renderer_femtovg::FemtoVGOpenGLRenderer as FemtoVGRenderer;
417 +         pub use i_slint_renderer_femtovg::FemtoVGRenderer as FemtoVGRenderer;
    |

error[E0432]: unresolved import `i_slint_renderer_femtovg::opengl`
   --> slint-1.16.1/lib.rs:422:43
    |
422 |         pub use i_slint_renderer_femtovg::opengl::OpenGLInterface;
    |                                           ^^^^^^ could not find `opengl` in `i_slint_renderer_femtovg`
    |
note: found an item that was configured out
   --> i-slint-renderer-femtovg-1.16.1/lib.rs:41:9
    |
 40 | #[cfg(feature = "opengl")]
    |       ------------------ the item is gated behind the `opengl` feature
 41 | pub mod opengl;
    |         ^^^^^^
```

### Reproducible Code (if applicable)

```slint

```

### Environment Details

- Slint Version: 1.16.1
- Platform/OS:
- Programming Language: rust
- Backend/Renderer:

**Comment by tronical** [comment]
Hi! Could you describe what features and you enable/disable in your Cargo.toml?

**Comment by MAlba124** [comment]
`default-features = false` and enabled `compat-1-2`, `std`, `renderer-femtovg`. (custom platform layer)

**Comment by tronical** [comment]
Thanks, I can reproduce that.
