### ISSUE TITLE
`Expression::StructFieldAccess's base expression is not an Object type`

### ISSUE THREAD

**Issue by ianhattendorf** [slint-ui/slint#8723]
### Bug Description

Compiling my project with the simplified `ui/mainwindow.slint` and `build.rs` results in the following compilation error:
```
% RUST_BACKTRACE=1 cargo check           
...                                                                                                                                 
  thread 'main' panicked at /home/ian/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/i-slint-compiler-1.11.0/generator/rust.rs:2333:18:
  Expression::StructFieldAccess's base expression is not an Object type
  stack backtrace:
     0: __rustc::rust_begin_unwind
               at /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/std/src/panicking.rs:697:5
     1: core::panicking::panic_fmt
               at /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/core/src/panicking.rs:75:14
     2: i_slint_compiler::generator::rust::compile_expression
     3: i_slint_compiler::generator::rust::compile_expression
     4: i_slint_compiler::generator::rust::compile_expression::{{closure}}
     5: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
     6: i_slint_compiler::generator::rust::compile_expression
     7: i_slint_compiler::generator::rust::handle_property_init
     8: i_slint_compiler::generator::rust::generate_sub_component
     9: i_slint_compiler::generator::rust::generate_item_tree
    10: i_slint_compiler::generator::rust::generate_public_component
    11: i_slint_compiler::generator::rust::generate::{{closure}}
    12: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
    13: i_slint_compiler::generator::rust::generate
    14: slint_build::compile_with_output_path
    15: slint_build::compile_with_config
    16: build_script_build::main
    17: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Reproducible Code (if applicable)

```slint
`ui/mainwindow.slint`:

export component Page inherits Rectangle {
    FocusScope {
        key-pressed(event) => {
            if (true) {
                if (false) {
                    return accept;
                } // else { // Wrapping this return accept or the reject below in an else "fixes" the compilation error
                    return accept;
                // }
            }
            if (event.text == Key.LeftArrow) {
                return accept;
            }
            return reject;
        }
    }
}


`build.rs`:
use slint_build::CompilerConfiguration;

fn main() {
    let config = CompilerConfiguration::new();
    slint_build::compile_with_config("ui/mainwindow.slint", config).unwrap();
}
```

### Environment Details

- Slint Version: 1.12 (working in 1.10, failing in 1.11)
- Platform/OS: Fedora Asahi Remix 42
- Programming Language: Rust
- Backend/Renderer: winit/skia

### Product Impact

Inconvenience

**Comment by ogoffart** [comment]
Thanks a lot for the bug report.
I suspect something is wrong in the pass that transform the returns.

**Comment by ianhattendorf** [comment]
Perfect, thanks for the quick fix.
