### ISSUE TITLE
i-slint-core 1.18.1 fails to compile for xtensa-esp32s3-none-elf: f32::rem_euclid is unavailable

### ISSUE THREAD

**Issue by joebnb** [slint-ui/slint#13560]
## Summary

  Slint 1.18.1 fails to compile for a bare-metal ESP32-S3 Rust target because
  `i-slint-core` calls `f32::rem_euclid()`, which is not available on the Xtensa
  target toolchain.

  ## Environment

  - Slint: `1.18.1`
  - Target: `xtensa-esp32s3-none-elf`
  - Toolchain: esp-rs Rust `1.97.0-nightly`
  - Build mode: `no_std`
  - Cargo configuration:

  ```toml
  [target.xtensa-esp32s3-none-elf]
  # target selected here

  [unstable]
  build-std = ["alloc", "core"]

  - Slint dependency:

  slint = { version = "=1.18.1", default-features = false, features = [
      "compat-1-18",
      "renderer-software",
      "software-renderer-path",
      "unsafe-single-threaded",
      "libm",
  ] }

  [build-dependencies]
  slint-build = "=1.18.1"

  ## Actual result

  cargo build --release fails with:

  error[E0599]: no method named `rem_euclid` found for type `f32` in the current scope
     --> .../i-slint-core-1.18.1/graphics/path.rs:329:25
      |
  329 |         let mut rem = t.rem_euclid(1.);
      |                         ^^^^^^^^^^

  ## Expected result

  Slint should compile for the xtensa-esp32s3-none-elf no_std target when the
  libm feature is enabled.

  ## Possible fix

  Elsewhere in i-slint-core, the code already uses
  num_traits::Euclid::rem_euclid(...) with a comment noting that
  f32::rem_euclid is not always available.

  Would replacing this call with the num_traits::Euclid version be the intended
  portable implementation?

  For example:

  let mut rem = num_traits::Euclid::rem_euclid(&t, &1.0);

  I can test a patch on ESP32-S3 hardware if useful.

### Reproducible Code (if applicable)

```slint

```

### Environment Details

- Slint Version:
- Platform/OS:
- Programming Language:
- Backend/Renderer:

**Comment by ogoffart** [comment]
Thanks for the bug report, this is caused by feature software-renderer-path 

(regression introduced in a481d0a83b2f6d0317e7e443dc3e91d19b2c6b90)
