### ISSUE TITLE
could not compile `memmap2` (lib)

### ISSUE THREAD

**Issue by hbhong** [slint-ui/slint#2989]
After upgrading to 1.10 from 1.0.2, I got many `memmap2` compile error 
Lang: Rust 1.72.0-nightly (49b6d9e17 2023-06-09)
platform: Ubuntu 22
target platform: ESP32C3

```
error: could not compile `memmap2` (lib) due to 36 previous errors
error[E0425]: cannot find value `MAP_FAILED` in crate `libc`
  --> <my_home>.cargo/registry/src/index.crates.io-6f17d22bba15001f/memmap2-0.6.2/src/unix.rs:93:29
   |
93 |             if ptr == libc::MAP_FAILED {
   |                             ^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `PROT_READ` in crate `libc`
   --> <my_home>.cargo/registry/src/index.crates.io-6f17d22bba15001f/memmap2-0.6.2/src/unix.rs:108:19
    |
108 |             libc::PROT_READ,
    |                   ^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `MAP_SHARED` in crate `libc`
   --> <my_home>.cargo/registry/src/index.crates.io-6f17d22bba15001f/memmap2-0.6.2/src/unix.rs:109:19
    |
109 |             libc::MAP_SHARED | populate,
    |                   ^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `PROT_READ` in crate `libc`
   --> <my_home>.cargo/registry/src/index.crates.io-6f17d22bba15001f/memmap2-0.6.2/src/unix.rs:119:19
    |
119 |             libc::PROT_READ | libc::PROT_EXEC,
    |                   ^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `PROT_EXEC` in crate `libc`
   --> <my_home>.cargo/registry/src/index.crates.io-6f17d22bba15001f/memmap2-0.6.2/src/unix.rs:119:37
    |
119 |             libc::PROT_READ | libc::PROT_EXEC,
    |                                     ^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `MAP_SHARED` in crate `libc`
   --> <my_home>.cargo/registry/src/index.crates.io-6f17d22bba15001f/memmap2-0.6.2/src/unix.rs:120:19
    |
120 |             libc::MAP_SHARED | populate,
    |                   ^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `PROT_READ` in crate `libc`
   --> <my_home>.cargo/registry/src/index.crates.io-6f17d22bba15001f/memmap2-0.6.2/src/unix.rs:130:19
    |
130 |             libc::PROT_READ | libc::PROT_WRITE,
    |                   ^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `PROT_WRITE` in crate `libc`
   --> <my_home>.cargo/registry/src/index.crates.io-6f17d22bba15001f/memmap2-0.6.2/src/unix.rs:130:37
    |
130 |             libc::PROT_READ | libc::PROT_WRITE,
    |                                     ^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `MAP_SHARED` in crate `libc`
   --> <my_home>.cargo/registry/src/index.crates.io-6f17d22bba15001f/memmap2-0.6.2/src/unix.rs:131:19
    |
131 |             libc::MAP_SHARED | populate,
    |                   ^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `PROT_READ` in crate `libc`
   --> <my_home>.cargo/registry/src/index.crates.io-6f17d22bba15001f/memmap2-0.6.2/src/unix.rs:141:19
    |
141 |             libc::PROT_READ | libc::PROT_WRITE,
    |                   ^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `PROT_WRITE` in crate `libc`
   --> <my_home>.cargo/registry/src/index.crates.io-6f17d22bba15001f/memmap2-0.6.2/src/unix.rs:141:37
    |
141 |             libc::PROT_READ | libc::PROT_WRITE,
    |                                     ^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `MAP_PRIVATE` in crate `libc`
   --> <my_home>.cargo/registry/src/index.crates.io-6f17d22bba15001f/memmap2-0.6.2/src/unix.rs:142:19
    |
142 |             libc::MAP_PRIVATE | populate,
    |                   ^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `PROT_READ` in crate `libc`
   --> <my_home>.cargo/registry/src/index.crates.io-6f17d22bba15001f/memmap2-0.6.2/src/unix.rs:157:19
    |
157 |             libc::PROT_READ,
    |                   ^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `MAP_PRIVATE` in crate `libc`
   --> <my_home>.cargo/registry/src/index.crates.io-6f17d22bba15001f/memmap2-0.6.2/src/unix.rs:158:19
    |
158 |             libc::MAP_PRIVATE | populate,
    |                   ^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `PROT_READ` in crate `libc`
   --> <my_home>.cargo/registry/src/index.crates.io-6f17d22bba15001f/memmap2-0.6.2/src/unix.rs:170:19
    |
170 |             libc::PROT_READ | libc::PROT_WRITE,
    |                   ^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `PROT_WRITE` in crate `libc`
   --> <my_home>.cargo/registry/src/index.crates.io-6f17d22bba15001f/memmap2-0.6.2/src/unix.rs:170:37
    |
170 |             libc::PROT_READ | libc::PROT_WRITE,
    |                                     ^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `MAP_PRIVATE` in crate `libc`
   --> <my_home>.cargo/registry/src/index.crates.io-6f17d22bba15001f/memmap2-0.6.2/src/unix.rs:171:19
    |
171 |             libc::MAP_PRIVATE | libc::MAP_ANON | stack | populate,
    |                   ^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `MAP_ANON` in crate `libc`
   --> <my_home>.cargo/registry/src/index.crates.io-6f17d22bba15001f/memmap2-0.6.2/src/unix.rs:171:39
    |
171 |             libc::MAP_PRIVATE | libc::MAP_ANON | stack | populate,
    |                                       ^^^^^^^^ not found in `libc`

error[E0425]: cannot find function `msync` in crate `libc`
    --> <my_home>.cargo/registry/src/index.crates.io-6f17d22bba15001f/memmap2-0.6.2/src/unix.rs:182:28
     |
182  |             unsafe { libc::msync(self.ptr.offset(offset), len as libc::size_t, libc::MS_SYNC) };
     |                            ^^^^^ help: a function with a similar name exists: `fsync`
     |
    ::: <my_home>.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.142/src/unix/mod.rs:1035:5
     |
1035 |     pub fn fsync(fd: ::c_int) -> ::c_int;
     |     ------------------------------------ similarly named function `fsync` defined here

error[E0425]: cannot find value `MS_SYNC` in crate `libc`
   --> <my_home>.cargo/registry/src/index.crates.io-6f17d22bba15001f/memmap2-0.6.2/src/unix.rs:182:86
    |
182 |             unsafe { libc::msync(self.ptr.offset(offset), len as libc::size_t, libc::MS_SYNC) };
    |                                                                                      ^^^^^^^ help: a constant with a similar name exists: `O_SYNC`
    |
   ::: <my_home>.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.142/src/unix/newlib/mod.rs:393:1
    |
393 | pub const O_SYNC: ::c_int = 8192;
    | ------------------------- similarly named constant `O_SYNC` defined here

error[E0425]: cannot find function `msync` in crate `libc`
    --> <my_home>.cargo/registry/src/index.crates.io-6f17d22bba15001f/memmap2-0.6.2/src/unix.rs:195:28
     |
195  |             unsafe { libc::msync(self.ptr.offset(offset), len as libc::size_t, libc::MS_ASYNC) };
     |                            ^^^^^ help: a function with a similar name exists: `fsync`
     |
    ::: <my_home>.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.142/src/unix/mod.rs:1035:5
     |
1035 |     pub fn fsync(fd: ::c_int) -> ::c_int;
     |     ------------------------------------ similarly named function `fsync` defined here

error[E0425]: cannot find value `MS_ASYNC` in crate `libc`
   --> <my_home>.cargo/registry/src/index.crates.io-6f17d22bba15001f/memmap2-0.6.2/src/unix.rs:195:86
    |
195 |             unsafe { libc::msync(self.ptr.offset(offset), len as libc::size_t, libc::MS_ASYNC) };
    |                                                                                      ^^^^^^^^ not found in `libc`

error[E0425]: cannot find function `mprotect` in crate `libc`
   --> <my_home>.cargo/registry/src/index.crates.io-6f17d22bba15001f/memmap2-0.6.2/src/unix.rs:209:22
    |
209 |             if libc::mprotect(ptr, len, prot) == 0 {
    |                      ^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `PROT_READ` in crate `libc`
   --> <my_home>.cargo/registry/src/index.crates.io-6f17d22bba15001f/memmap2-0.6.2/src/unix.rs:218:29
    |
218 |         self.mprotect(libc::PROT_READ)
    |                             ^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `PROT_READ` in crate `libc`
   --> <my_home>.cargo/registry/src/index.crates.io-6f17d22bba15001f/memmap2-0.6.2/src/unix.rs:222:29
    |
222 |         self.mprotect(libc::PROT_READ | libc::PROT_EXEC)
    |                             ^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `PROT_EXEC` in crate `libc`
   --> <my_home>.cargo/registry/src/index.crates.io-6f17d22bba15001f/memmap2-0.6.2/src/unix.rs:222:47
    |
222 |         self.mprotect(libc::PROT_READ | libc::PROT_EXEC)
    |                                               ^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `PROT_READ` in crate `libc`
   --> <my_home>.cargo/registry/src/index.crates.io-6f17d22bba15001f/memmap2-0.6.2/src/unix.rs:226:29
    |
226 |         self.mprotect(libc::PROT_READ | libc::PROT_WRITE)
    |                             ^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `PROT_WRITE` in crate `libc`
   --> <my_home>.cargo/registry/src/index.crates.io-6f17d22bba15001f/memmap2-0.6.2/src/unix.rs:226:47
    |
226 |         self.mprotect(libc::PROT_READ | libc::PROT_WRITE)
    |                                               ^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find function `madvise` in crate `libc`
   --> <my_home>.cargo/registry/src/index.crates.io-6f17d22bba15001f/memmap2-0.6.2/src/unix.rs:249:22
    |
249 |             if libc::madvise(self.ptr.offset(offset), len, advice as i32) != 0 {
    |                      ^^^^^^^ not found in `libc`

error[E0425]: cannot find value `_SC_PAGESIZE` in crate `libc`
   --> <my_home>.cargo/registry/src/index.crates.io-6f17d22bba15001f/memmap2-0.6.2/src/unix.rs:301:58
    |
301 |             let page_size = unsafe { libc::sysconf(libc::_SC_PAGESIZE) as usize };
    |                                                          ^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `MADV_NORMAL` in crate `libc`
  --> <my_home>.cargo/registry/src/index.crates.io-6f17d22bba15001f/memmap2-0.6.2/src/advice.rs:13:20
   |
13 |     Normal = libc::MADV_NORMAL,
   |                    ^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `MADV_RANDOM` in crate `libc`
  --> <my_home>.cargo/registry/src/index.crates.io-6f17d22bba15001f/memmap2-0.6.2/src/advice.rs:19:20
   |
19 |     Random = libc::MADV_RANDOM,
   |                    ^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `MADV_SEQUENTIAL` in crate `libc`
  --> <my_home>.cargo/registry/src/index.crates.io-6f17d22bba15001f/memmap2-0.6.2/src/advice.rs:26:24
   |
26 |     Sequential = libc::MADV_SEQUENTIAL,
   |                        ^^^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `MADV_WILLNEED` in crate `libc`
  --> <my_home>.cargo/registry/src/index.crates.io-6f17d22bba15001f/memmap2-0.6.2/src/advice.rs:32:22
   |
32 |     WillNeed = libc::MADV_WILLNEED,
   |                      ^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `MADV_DONTNEED` in crate `libc`
  --> <my_home>.cargo/registry/src/index.crates.io-6f17d22bba15001f/memmap2-0.6.2/src/advice.rs:63:22
   |
63 |     DontNeed = libc::MADV_DONTNEED,
   |                      ^^^^^^^^^^^^^ not found in `libc`

error: aborting due to 35 previous errors
```

**Comment by hbhong** [comment]
sorry, seem it isn't due to 1.1.0 but I'm calling the new function `load_from_svg_data`, but how to fix this error?  Many thanks for any help.

**Comment by ogoffart** [comment]
> target platform: ESP32C3

What kind of standard library support does this platform have?
The `svg` feature might not be compatible with that platform because the svg dependency we use might not work on it.

**Comment by hbhong** [comment]
@ogoffart  thanks a lot
The ESP32 supports std/no-std(https://github.com/esp-rs), the crate starts with `esp-idf`-XXX is `std`, and  starts with `esp`-XXX is `no-std`(Bare metal) 

>The svg feature might not be compatible with that platform because the svg dependency we use might not work on it.
I think it is root reason for this issue.

**Comment by connor-mcnaboe** [comment]
I am running into the same issue while trying to to compile for the ESP32C3 platform. Unfortunately I must be a bit slow because i am not following @hbhong's solution to this issue. What updates were made to your project to account for the differences in the crate names?

**Comment by tronical** [comment]
There may be different reasons, but one potential issue can be that when being virtual workspaces with Cargo you still need to opt into using the new resolver via `resolver = “2”` in your workspace. Otherwise dependencies like that get selected.
