### ISSUE TITLE
Broken compiling on 1.13.0

### ISSUE THREAD

**Issue by Szybet** [slint-ui/slint#9321]
### Bug Description

I'm cross compiling to `aarch64-unknown-linux-gnu` with those features enabled:

`["slint/std", "slint/compat-1-2", "slint/backend-linuxkms-noseat", "slint/renderer-femtovg"]` + log

on 1.13.0 this happens:
```
error[E0433]: failed to resolve: could not find `opengl` in `i_slint_renderer_femtovg`
  --> /root/.cargo/git/checkouts/slint-774a37e469fae6bf/9b0b620/internal/backends/linuxkms/renderer/femtovg.rs:23:77
   |
23 |         i_slint_renderer_femtovg::FemtoVGRenderer<i_slint_renderer_femtovg::opengl::OpenGLBackend>,
   |                                                                             ^^^^^^ could not find `opengl` in `i_slint_renderer_femtovg`
   |
note: found an item that was configured out
  --> /root/.cargo/git/checkouts/slint-774a37e469fae6bf/9b0b620/internal/renderers/femtovg/lib.rs:40:9
   |
40 | pub mod opengl;
   |         ^^^^^^
note: the item is gated behind the `opengl` feature
  --> /root/.cargo/git/checkouts/slint-774a37e469fae6bf/9b0b620/internal/renderers/femtovg/lib.rs:39:7
   |
39 | #[cfg(feature = "opengl")]
   |       ^^^^^^^^^^^^^^^^^^

error[E0433]: failed to resolve: could not find `opengl` in `i_slint_renderer_femtovg`
   --> /root/.cargo/git/checkouts/slint-774a37e469fae6bf/9b0b620/internal/backends/linuxkms/renderer/femtovg.rs:118:39
    |
118 | unsafe impl i_slint_renderer_femtovg::opengl::OpenGLInterface for GlContextWrapper {
    |                                       ^^^^^^ could not find `opengl` in `i_slint_renderer_femtovg`
    |
note: found an item that was configured out
   --> /root/.cargo/git/checkouts/slint-774a37e469fae6bf/9b0b620/internal/renderers/femtovg/lib.rs:40:9
    |
40  | pub mod opengl;
    |         ^^^^^^
note: the item is gated behind the `opengl` feature
   --> /root/.cargo/git/checkouts/slint-774a37e469fae6bf/9b0b620/internal/renderers/femtovg/lib.rs:39:7
    |
39  | #[cfg(feature = "opengl")]
    |       ^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0433`.
error: could not compile `i-slint-backend-linuxkms` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
```
On 1.12.1 as in `slint = { version = "=1.12.1", default-features = false }` the `=` is needed to actually compile on 1.12.1, it works, compiles just fine also runs just fine using opengl

reproducing this issue would be hard, as a special sysroot is required

### Reproducible Code (if applicable)

```slint

```

### Environment Details

- Slint Version: 1.13.0
- Platform/OS: Linux
- Programming Language: Rust
- Backend/Renderer: `backend-linuxkms-noseat` and `renderer-femtovg`

### Product Impact

open source OS for the pinenote
