### PR TITLE
fix(deps): require const-field-offset 0.2.1 so that generated code builds

### PR DESCRIPTION
**Pull request by tkng**
## Bug Description

Since 1.18.0, the Rust code generated by `slint-build` / `slint!` can call
`sp::compose_field_offsets(...)`: `internal/compiler/generator/rust.rs` emits it
when building the const `item_array` for `ItemTreeNode::Item` nodes that live
inside a nested sub-component — e.g. a widget or custom component inside a
`Dialog`, `PopupWindow`, or `for` repeater.

`sp` is `slint::private_unstable_api::re_exports`, where `compose_field_offsets`
is only reachable transitively:

```
re_exports: pub use vtable::{self, *}
  -> vtable 0.5.0: pub use const_field_offset::*   (src/lib.rs:63)
    -> const_field_offset::compose_field_offsets   (added in 0.2.1)
```

But the declared minimums are `0.2`/`0.2.0`, and `compose_field_offsets` was only
added in const-field-offset **0.2.1** (see its CHANGELOG). When the dependency
resolves to 0.2.0, the generated code fails to compile:

```
error[E0425]: cannot find function `compose_field_offsets` in module `sp`
```

Two cases hit this:

- a `Cargo.lock` that already holds `const-field-offset` 0.2.0, e.g. upgrading an
  existing project from slint 1.17 to 1.18 (cargo keeps the locked 0.2.0 since it
  satisfies the declared `0.2.0` bound)
- `cargo +nightly build -Z minimal-versions`

This couldn't be caught in-repo or by CI: the manifests use a `path` dependency
to `helper_crates/const-field-offset`, so builds in this repository always
resolve to the local 0.2.1 crate. A fresh `cargo add slint@1.18` today also
picks 0.2.1 and compiles, which is why the release sailed through.

## Reproducible Code

`ui/app.slint`:

```slint
component Inner {
    Rectangle {}
}

export component AppWindow inherits Window {
    Inner {}
}
```

`Cargo.toml`: `slint = "1.18"` + `slint-build = "1.18"` (build-dep), the usual
`build.rs` + `slint::include_modules!()` main.rs, then:

```console
$ cargo update -p const-field-offset --precise 0.2.0
$ cargo build
error[E0425]: cannot find function `compose_field_offsets` in module `sp`
```

(`cargo +nightly build -Z minimal-versions` fails identically, without the
manual downgrade.)

## Environment Details

- Slint Version: 1.18.0 (regression vs 1.17.1; codegen introduced in #12369)
- Platform/OS: Linux x86_64 (platform-independent)
- Programming Language: Rust
- Backend/Renderer: any (the error is in generated code, before backend use)

## Proposed Fix

Raise the declared minimum to `0.2.1` in the manifests depending on
`const-field-offset` (`api/rs/slint`, `internal/core`, `internal/backends/qt`,
`internal/renderers/femtovg`, `internal/renderers/skia`, `helper_crates/vtable`)

- [x] I license this and all my future contributions to Slint under the [MIT-0 license](https://opensource.org/license/mit-0). They are my own work, and no third party (such as my employer) holds rights to them.

### CODE REVIEW

**Review by ogoffart — APPROVED** [review]

**Comment by ogoffart** [comment]
Thanks!
