### PR TITLE
Rust codegen: fix global access in repeated component layout accessors

### LINKED ISSUE #13093: Regression from 1.17.1. Master Rust codegen emits invalid global access for repeated components with explicit no-wrap text
### Bug Description

Slint master revision `72cf74306784e7d15374639ef110c1bb85c21cb0` generates invalid Rust code when:

1. A repeated component is placed inside a layout.
2. The component’s size depends on a global property.
3. The component contains `Text { wrap: no-wrap; }`.

The generated code accesses `global_Metrics` directly on the repeated-component wrapper, although that wrapper does not contain such a field.

Mini example project attached 

[slint-master-repro.zip](https://github.com/user-attachments/files/31561859/slint-master-repro.zip)

### Reproducible Code (if applicable)

```slint

```

### Environment Details

- Slint Version: 1.18 master
- Platform/OS: linux
- Programming Language: Rust
- Backend/Renderer: Software

### Product Impact

_No response_

### PR DESCRIPTION
**Pull request by ogoffart**
The evaluation context for a repeated component used `_self` as the global access, so the synthesized cross-axis layout-info accessor emitted `_self.global_Foo` instead of `_self.globals().global_Foo`. The repeated item tree wrapper has no such field, so the generated code failed to compile when a repeated cell in a layout sized itself from a global and contained a non-wrapping Text.

This is a regression from commit e0f0179e45, which added the box-layout cross-axis accessor that consumes this context.

Fixes: #13093

Also fix panic when a component named Row is a GridLayout cell

### CODE REVIEW

**Comment by ogoffart** [comment]
The two commits are unrelated, but Claude found the panic when trying to add test for this issue.

**Review by tronical — APPROVED** [review]
Both commits look good to me
