### ISSUE TITLE
Conditional/state expression with differently-sized array literals no longer compiles

### ISSUE THREAD

**Issue by abalogstromer** [slint-ui/slint#12421]
### Bug Description

When a property of array type is assigned array literals of different lengths in a conditional expression (e.g. `states` or `? : `), the generated C++ no longer compiles. This is the compilation error:
`error: operands to '?:' have different types
  'std::shared_ptr<slint::private_api::ArrayModel<3, ButtonProps> >' and
  'std::shared_ptr<slint::private_api::ArrayModel<0, ButtonProps> >'`

In 1.17 it generates simplified ternary operation, but c++ expects both operands to be of the same type.
In previous version where it worked it would generate an inline function with a declared return type.

### Reproducible Code (if applicable)

```slint
export component Example inherits Window {
    in property <int> mode;
    in-out property <[length]> vals: mode == 1 ? [10px, 20px, 30px]
                                   : mode == 2 ? [40px, 50px]
                                   : [];
    out property <length> first: vals[0];
}
```

### Environment Details

- Slint Version: 1.17.1 (issue backtracked to first appearance in version 1.15)
- Platform/OS: Linux
- Programming Language: C++
- Backend/Renderer: -

**Comment by ogoffart** [comment]
Thanks for filling a bug.

The problem is actually not reproducible in master because #11614 actually fixed it as a side effect.

I made a test in #12424

We could still make a fix like so that would also work in the 1.17 branch 

But None of the other types reproduce this, so i'm torn.

```diff
diff --git a/internal/compiler/generator/cpp.rs b/internal/compiler/generator/cpp.rs
index 41e71e3b31..0cabf91a37 100644
--- a/internal/compiler/generator/cpp.rs
+++ b/internal/compiler/generator/cpp.rs
@@ -4195,6 +4195,12 @@ fn compile_expression(expr: &llr::Expression, ctx: &EvaluationContext) -> String
             let false_code = compile_expression(false_expr, ctx);
             if ty == Type::Void {
                 format!("if ({cond_code}) {{ {true_code}; }} else {{ {false_code}; }}")
+            } else if let Some(cpp_ty) = ty.cpp_type() {
+                // Cast both branches to the common type so the ternary compiles even when they
+                // have different but convertible C++ types.
+                format!(
+                    "({cond_code} ? static_cast<{cpp_ty}>({true_code}) : static_cast<{cpp_ty}>({false_code}))"
+                )
             } else {
                 format!("({cond_code} ? {true_code} : {false_code})")
             }
``` 

@tronical:  what do you think?

**Comment by tronical** [comment]
> Thanks for filling a bug.
> 
> The problem is actually not reproducible in master because [#11614](https://github.com/slint-ui/slint/pull/11614) actually fixed it as a side effect.
> 
> I made a test in [#12424](https://github.com/slint-ui/slint/pull/12424)
> 
> We could still make a fix like so that would also work in the 1.17 branch
> 
> But None of the other types reproduce this, so i'm torn.
> 
> diff --git a/internal/compiler/generator/cpp.rs b/internal/compiler/generator/cpp.rs
> index 41e71e3b31..0cabf91a37 100644
> --- a/internal/compiler/generator/cpp.rs
> +++ b/internal/compiler/generator/cpp.rs
> @@ -4195,6 +4195,12 @@ fn compile_expression(expr: &llr::Expression, ctx: &EvaluationContext) -> String
>              let false_code = compile_expression(false_expr, ctx);
>              if ty == Type::Void {
>                  format!("if ({cond_code}) {{ {true_code}; }} else {{ {false_code}; }}")
> +            } else if let Some(cpp_ty) = ty.cpp_type() {
> +                // Cast both branches to the common type so the ternary compiles even when they
> +                // have different but convertible C++ types.
> +                format!(
> +                    "({cond_code} ? static_cast<{cpp_ty}>({true_code}) : static_cast<{cpp_ty}>({false_code}))"
> +                )
>              } else {
>                  format!("({cond_code} ? {true_code} : {false_code})")
>              }
> [@tronical](https://github.com/tronical): what do you think?

I'm also torn TBH. On the one hand if this is fixed it's fixed, on the other hand it really sucks if a user gets blocked due to generated code not compiling, so being pro-active is good.

**Comment by ogoffart** [comment]
I'll close this since it is fixed.
