### PR TITLE
demos: fix home-automation esp-idf build on GCC 14 (ESP-IDF 5.4+)

### PR DESCRIPTION
**Pull request by aurindam**
`demos/home-automation/esp-idf` fails to build for the ESP32-P4 on current ESP-IDF (5.4+, GCC 14):

```
esp_lcd_touch_gt911.h:68:5: error: designator order for field
'esp_lcd_panel_io_i2c_config_t::dev_addr' does not match declaration order
  … in expansion of macro 'ESP_LCD_TOUCH_IO_I2C_GT911_CONFIG'
```

Fix: replace the macro with an equivalent initializer in declaration order (identical values — it also folds in the `scl_speed_hz` the next line set anyway). No behavior change.

### CODE REVIEW

**Review by tronical — COMMENTED** [review]
The commit message blames esp-idf and gcc 14, but the root cause is https://github.com/espressif/esp-bsp/issues/797 . It's definitely preferred to use `ESP_LCD_TOUCH_IO_I2C_GT911_CONFIG()` instead of spelling out the fields though, and hopefully this will be fixed upstream soon. I'll see if it can be pinned or worked around otherwise.

**Comment by tronical** [comment]
I've found an alternative fix and I'll also add CI coverage.
