### PR TITLE
Fix slint::platform::femtovg_renderer::FemtoVGRenderer not always bei…

### LINKED ISSUE #11530: FemtoVGRenderer is no longer available
### Bug Description

Enabling `slint/renderer-femtovg` does not work in 1.16.

```
error[E0432]: unresolved import `i_slint_renderer_femtovg::FemtoVGOpenGLRenderer`
   --> slint-1.16.1/lib.rs:417:17
    |
417 |         pub use i_slint_renderer_femtovg::FemtoVGOpenGLRenderer as FemtoVGRenderer;
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `FemtoVGOpenGLRenderer` in the root
    |
note: found an item that was configured out
   --> i-slint-renderer-femtovg-1.16.1/lib.rs:584:10
    |
583 | #[cfg(feature = "opengl")]
    |       ------------------ the item is gated behind the `opengl` feature
584 | pub type FemtoVGOpenGLRenderer = FemtoVGRenderer<opengl::OpenGLBackend>;
    |          ^^^^^^^^^^^^^^^^^^^^^
help: a similar name exists in the module
    |
417 -         pub use i_slint_renderer_femtovg::FemtoVGOpenGLRenderer as FemtoVGRenderer;
417 +         pub use i_slint_renderer_femtovg::FemtoVGRenderer as FemtoVGRenderer;
    |

error[E0432]: unresolved import `i_slint_renderer_femtovg::opengl`
   --> slint-1.16.1/lib.rs:422:43
    |
422 |         pub use i_slint_renderer_femtovg::opengl::OpenGLInterface;
    |                                           ^^^^^^ could not find `opengl` in `i_slint_renderer_femtovg`
    |
note: found an item that was configured out
   --> i-slint-renderer-femtovg-1.16.1/lib.rs:41:9
    |
 40 | #[cfg(feature = "opengl")]
    |       ------------------ the item is gated behind the `opengl` feature
 41 | pub mod opengl;
    |         ^^^^^^
```

### Reproducible Code (if applicable)

```slint

```

### Environment Details

- Slint Version: 1.16.1
- Platform/OS:
- Programming Language: rust
- Backend/Renderer:

### Product Impact

_No response_

### PR DESCRIPTION
**Pull request by tronical**
…ng accessible

Just using default-features = false and enabling compat-1-2 and renderer-femtovg, used to - and should - give access to this API.

Fixes #11530

### CODE REVIEW

**Review by ogoffart — APPROVED** [review]

**Comment by ogoffart** [comment]
What about the slint-interpreter and slint-cpp and other crate that re-expose the backend features?

**Comment by tronical** [comment]
> What about the slint-interpreter and slint-cpp and other crate that re-expose the backend features?

They're okay, the backend selector crate forwards to for example winit or linuxkms, which in turn enable the OpenGL feature. This is only about API access to the FemtoVG GL renderer type, which only happens through the slint crate.
