### PR TITLE
ESP32-S3-BOX-3 support - update to esp-hal 1.0.0

### PR DESCRIPTION
**Pull request by georgik**
The example/mcu-board-support was updated with ESP32-S3-BOX-3 support and newer esp-hal 1.0.0.

The board also contains GT911 which has RST connected to shared pin, so it requires either handling of address configuration using RST and INT or fallback mechanism to check two addresses for GT911 on I2C. (This part could be refined in the future).

Timer was implmented using now and storing timer0 in the struct.

I welcome discussion about this changes, so that we can refine it to the way how Slint framework is built.

The working example can be tested from repo: https://github.com/georgik/esp32-slint-demo

Simply:
```
cargo r -r
```

### CODE REVIEW

File: examples/mcu-board-support/esp32_s3_box_3.rs [hunk 1]
```diff
@@ -0,0 +1,354 @@
...
+        .unwrap()
+        .with_sda(peripherals.GPIO8)
+        .with_scl(peripherals.GPIO18);
+
+        // Initialize the touch driver.
+        let mut touch = Gt911Blocking::new(ESP_LCD_TOUCH_IO_I2C_GT911_ADDRESS);
+        match touch.init(&mut i2c) {
+            Ok(_) => info!("Touch initialized"),
+            Err(e) => {
+                info!("Touch initialization failed: {:?}", e);
```
Comment (WilstonOreo) [inline examples/mcu-board-support/esp32_s3_box_3.rs:232]: `warning!()` might be better here

File: examples/mcu-board-support/esp32_s3_box_3.rs [hunk 2]
```diff
@@ -0,0 +1,354 @@
...
+        // Update the display with the rendered line.
+        self.display
+            .set_pixels(
+                range.start as u16,
+                line as u16,
+                range.end as u16,
+                line as u16,
+                buffer
+                    .iter()
+                    .map(|x| embedded_graphics_core::pixelcolor::raw::RawU16::new(x.0).into()),
```
Comment (WilstonOreo) [inline examples/mcu-board-support/esp32_s3_box_3.rs:350]: Total pro would be to implement the [`TargetPixel` trait](https://docs.slint.dev/latest/docs/rust/slint/platform/software_renderer/trait.TargetPixel) for `embedded_graphics_core::pixelcolor::raw::RawU16`. Might improve rendering performance

File: examples/mcu-board-support/esp32_s3_box_3.rs [hunk 3]
```diff
@@ -0,0 +1,354 @@
...
+                });
+
+                if window.has_active_animations() {
+                    continue;
+                }
+            }
+        }
+    }
+
+    fn debug_log(&self, arguments: core::fmt::Arguments) {
```
Comment (WilstonOreo) [inline examples/mcu-board-support/esp32_s3_box_3.rs:313]: This function can be removed

File: examples/mcu-board-support/Cargo.toml [hunk 4]
```diff
@@ -119,6 +132,11 @@ pin-weak = { version = "1", default-features = false }
 rgb = "0.8.27"
 cfg-if = "1"
 
+
+esp-hal = { version = "1.0.0-beta.0", features = ["esp32s3", "unstable"], optional = true }
+log = "0.4.27"
+embedded-graphics-framebuf = "0.5.0"
```
Comment (tronical) [inline examples/mcu-board-support/Cargo.toml:138]: This looks like it's not needed?

File: examples/mcu-board-support/Cargo.toml [hunk 5]
```diff
@@ -119,6 +132,11 @@ pin-weak = { version = "1", default-features = false }
 rgb = "0.8.27"
 cfg-if = "1"
 
+
+esp-hal = { version = "1.0.0-beta.0", features = ["esp32s3", "unstable"], optional = true }
+log = "0.4.27"
```
Comment (tronical) [inline examples/mcu-board-support/Cargo.toml:137]: This should be an optional dependency and enabled for `esp32-s3-box-3`.

File: examples/mcu-board-support/esp32_s3_box_3.rs [hunk 6]
```diff
@@ -0,0 +1,354 @@
...
+    ) -> Result<Rc<dyn slint::platform::WindowAdapter>, slint::PlatformError> {
+        let window = slint::platform::software_renderer::MinimalSoftwareWindow::new(
+            slint::platform::software_renderer::RepaintBufferType::ReusedBuffer,
+        );
+        self.window.replace(Some(window.clone()));
+        Ok(window)
+    }
+
+    fn duration_since_start(&self) -> core::time::Duration {
+        let ts = self.timer_state.borrow();
```
Comment (MabezDev) [inline examples/mcu-board-support/esp32_s3_box_3.rs:95]: You can remove all the code associated with this here, with the timing primitives from https://docs.espressif.com/projects/rust/esp-hal/1.0.0-beta.0/esp32s3/esp_hal/time/index.html

I think `core::time::Duration::from_secs(Instant::now().duration_since_epoch().as_secs())` should do it.

File: examples/mcu-board-support/esp32_s3_box_3.rs [hunk 7]
```diff
@@ -0,0 +1,354 @@
...
+use esp_println::logger::init_logger_from_env;
+use gt911::Gt911Blocking;
+use log::{error, info};
+use mipidsi::options::{ColorOrder, Orientation, Rotation};
+use slint::platform::PointerEventButton;
+use slint::platform::WindowEvent;
+
+struct TimerState {
+    start_instant: Instant,
+    timer0: Option<esp_hal::timer::timg::Timer>,
```
Comment (MabezDev) [inline examples/mcu-board-support/esp32_s3_box_3.rs:37]: No need to waste a timer here, see below

**Review by MabezDev — CHANGES_REQUESTED** [review]

**Comment by georgik** [comment]
@MabezDev The demo application is using the [following code](https://github.com/slint-ui/slint/blob/master/demos/printerdemo_mcu/main.rs#L35)
```
#[mcu_board_support::entry]
fn main() -> ! {
```

This was working in previous hal, but in esp-hal 1.0.0 is was exposed as `#[main]` which is proc macro. This will result in dragging `esp_hal` dependency to the application and it's necessary to add a dependency on esp-hal directly to application, which was not the case before. [Here's the `Cargo.toml`](https://github.com/slint-ui/slint/pull/8112/files#diff-fa53c87e42dcb237c2a89a23a0bbf6e4be065d9617df5d20d1903de6590d814cR29)

Any idea how to resolve the situation in case of proc macro?

**Comment by MabezDev** [comment]
Why not just rexport `main` as `entry` in your `mcu_board_support` crate? Is it because it's a proc macro that it's not possible?

**Comment by MabezDev** [comment]
> @MabezDev That's the current solution. The only problem is that it's necessary to have esp-hal as a dependency on application level. Otherwise resolution of `esp_hal::main fails`:
> 
> ```
> error[E0433]: failed to resolve: use of undeclared crate or module `esp_hal`
>   --> demos/printerdemo_mcu/main.rs:36:1
>    |
> 36 | #[mcu_board_support::entry]
>    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `esp_hal`
> ```

I see, could you file an issue against esp-rs/esp-hal please? I think this is something we want to support.

File: examples/mcu-board-support/esp32_s3_box_3.rs (hunk 6 above)
Comment (georgik) [reply examples/mcu-board-support/esp32_s3_box_3.rs:95]: Great. It works, just it was necessary to use as_millis, otherwise animations were too slow.

**Review by tronical — APPROVED** [review]
